version: 2.1

executors:
  go-exec:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:<< parameters.go-version >>
    working_directory: /go/src/github.com/hbish/smex

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  publish_to_github:
    steps:
      - add_ssh_keys
      - run:
          name: create release
          command: make release-ci

jobs:
  go-build:
    parameters:
      go-version:
        type: string
    executor:
      name: go-exec
      go-version: << parameters.go-version >>
    steps:
      - checkout
      - go_mod_download
      - run:
          name: Run Test & Lint
          command: make test-ci
  go-release:
    parameters:
      go-version:
        type: string
    executor:
      name: go-exec
      go-version: << parameters.go-version >>
    steps:
      - run:
          name: Build Artifacts
          command: make build-ci
      - publish_to_github

workflows:
  version: 2
  main:
    jobs:
      - go-build:
          go-version: "1.14"
      - go-release:
          go-version: "1.14"
          filters:
            branches:
              only: master

